--[[
  Reference:
  https://code.visualstudio.com/api/references/icons-in-labels
--]]

---@class vsCodeProductIconConfig @Table of VS Code Product Icon Configuration
---@field name string @Name of the codicon value to use
---@field description string @Description provided by Visual Studio

---@class vsCodeProductIconConfigExtended : vsCodeProductIconConfig @Extended vsCodeProductIconConfig with information from the codicon library
---@field icon string @The literal codicon icon
---@field unicode integer @The unicode value for the codicon icon

---@alias vsCodeProductIconConfigTable table<string, vsCodeProductIconConfig>

---@type vsCodeProductIconConfigTable
return {
  ['accounts-view-bar-icon']                    = { name = 'account',                                 description = [[Accounts icon in the view bar.]]                                                         } ,
  ['breakpoints-activate']                      = { name = 'activate-breakpoints',                    description = [[Icon for the activate action in the breakpoints view.]]                                  } ,
  ['breakpoints-remove-all']                    = { name = 'close-all',                               description = [[Icon for the Remove All action in the breakpoints view.]]                                } ,
  ['breakpoints-view-icon']                     = { name = 'debug-alt',                               description = [[View icon of the breakpoints view.]]                                                     } ,
  ['callhierarchy-incoming']                    = { name = 'call-incoming',                           description = [[Icon for incoming calls in the call hierarchy view.]]                                    } ,
  ['callhierarchy-outgoing']                    = { name = 'call-outgoing',                           description = [[Icon for outgoing calls in the call hierarchy view.]]                                    } ,
  ['callstack-view-icon']                       = { name = 'debug-alt',                               description = [[View icon of the call stack view.]]                                                      } ,
  ['callstack-view-session']                    = { name = 'bug',                                     description = [[Icon for the session icon in the call stack view.]]                                      } ,
  ['comments-view-icon']                        = { name = 'comment-discussion',                      description = [[View icon of the comments view.]]                                                        } ,
  ['debug-breakpoint']                          = { name = 'debug-breakpoint',                        description = [[Icon for breakpoints.]]                                                                  } ,
  ['debug-breakpoint-conditional']              = { name = 'debug-breakpoint-conditional',            description = [[Icon for conditional breakpoints.]]                                                      } ,
  ['debug-breakpoint-conditional-disabled']     = { name = 'debug-breakpoint-conditional-disabled',   description = [[Icon for disabled conditional breakpoints.]]                                             } ,
  ['debug-breakpoint-conditional-unverified']   = { name = 'debug-breakpoint-conditional-unverified', description = [[Icon for unverified conditional breakpoints.]]                                           } ,
  ['debug-breakpoint-data']                     = { name = 'debug-breakpoint-data',                   description = [[Icon for data breakpoints.]]                                                             } ,
  ['debug-breakpoint-data-disabled']            = { name = 'debug-breakpoint-data-disabled',          description = [[Icon for disabled data breakpoints.]]                                                    } ,
  ['debug-breakpoint-data-unverified']          = { name = 'debug-breakpoint-data-unverified',        description = [[Icon for unverified data breakpoints.]]                                                  } ,
  ['debug-breakpoint-disabled']                 = { name = 'debug-breakpoint-disabled',               description = [[Icon for disabled breakpoints.]]                                                         } ,
  ['debug-breakpoint-function']                 = { name = 'debug-breakpoint-function',               description = [[Icon for function breakpoints.]]                                                         } ,
  ['debug-breakpoint-function-disabled']        = { name = 'debug-breakpoint-function-disabled',      description = [[Icon for disabled function breakpoints.]]                                                } ,
  ['debug-breakpoint-function-unverified']      = { name = 'debug-breakpoint-function-unverified',    description = [[Icon for unverified function breakpoints.]]                                              } ,
  ['debug-breakpoint-log']                      = { name = 'debug-breakpoint-log',                    description = [[Icon for log breakpoints.]]                                                              } ,
  ['debug-breakpoint-log-disabled']             = { name = 'debug-breakpoint-log-disabled',           description = [[Icon for disabled log breakpoint.]]                                                      } ,
  ['debug-breakpoint-log-unverified']           = { name = 'debug-breakpoint-log-unverified',         description = [[Icon for unverified log breakpoints.]]                                                   } ,
  ['debug-breakpoint-unsupported']              = { name = 'debug-breakpoint-unsupported',            description = [[Icon for unsupported breakpoints.]]                                                      } ,
  ['debug-breakpoint-unverified']               = { name = 'debug-breakpoint-unverified',             description = [[Icon for unverified breakpoints.]]                                                       } ,
  ['debug-collapse-all']                        = { name = 'collapse-all',                            description = [[Icon for the collapse all action in the debug views.]]                                   } ,
  ['debug-configure']                           = { name = 'gear',                                    description = [[Icon for the debug configure action.]]                                                   } ,
  ['debug-console']                             = { name = 'debug-console',                           description = [[Icon for the debug console open action.]]                                                } ,
  ['debug-console-clear-all']                   = { name = 'clear-all',                               description = [[Icon for the clear all action in the debug console.]]                                    } ,
  ['debug-console-evaluation-input']            = { name = 'arrow-small-right',                       description = [[Icon for the debug evaluation input marker.]]                                            } ,
  ['debug-console-evaluation-prompt']           = { name = 'chevron-right',                           description = [[Icon for the debug evaluation prompt.]]                                                  } ,
  ['debug-console-view-icon']                   = { name = 'debug-console',                           description = [[View icon of the debug console view.]]                                                   } ,
  ['debug-continue']                            = { name = 'debug-continue',                          description = [[Icon for the debug continue action.]]                                                    } ,
  ['debug-disconnect']                          = { name = 'debug-disconnect',                        description = [[Icon for the debug disconnect action.]]                                                  } ,
  ['debug-gripper']                             = { name = 'gripper',                                 description = [[Icon for the debug bar gripper.]]                                                        } ,
  ['debug-hint']                                = { name = 'debug-hint',                              description = [[Icon for breakpoint hints shown on hover in editor glyph margin.]]                       } ,
  ['debug-pause']                               = { name = 'debug-pause',                             description = [[Icon for the debug pause action.]]                                                       } ,
  ['debug-restart']                             = { name = 'debug-restart',                           description = [[Icon for the debug restart action.]]                                                     } ,
  ['debug-restart-frame']                       = { name = 'debug-restart-frame',                     description = [[Icon for the debug restart frame action.]]                                               } ,
  ['debug-reverse-continue']                    = { name = 'debug-reverse-continue',                  description = [[Icon for the debug reverse continue action.]]                                            } ,
  ['debug-stackframe']                          = { name = 'debug-stackframe',                        description = [[Icon for a stackframe shown in the editor glyph margin.]]                                } ,
  ['debug-stackframe-focused']                  = { name = 'debug-stackframe-focused',                description = [[Icon for a focused stackframe  shown in the editor glyph margin.]]                       } ,
  ['debug-start']                               = { name = 'debug-start',                             description = [[Icon for the debug start action.]]                                                       } ,
  ['debug-step-back']                           = { name = 'debug-step-back',                         description = [[Icon for the debug step back action.]]                                                   } ,
  ['debug-step-into']                           = { name = 'debug-step-into',                         description = [[Icon for the debug step into action.]]                                                   } ,
  ['debug-step-out']                            = { name = 'debug-step-out',                          description = [[Icon for the debug step out action.]]                                                    } ,
  ['debug-step-over']                           = { name = 'debug-step-over',                         description = [[Icon for the debug step over action.]]                                                   } ,
  ['debug-stop']                                = { name = 'debug-stop',                              description = [[Icon for the debug stop action.]]                                                        } ,
  ['default-view-icon']                         = { name = 'window',                                  description = [[Default view icon.]]                                                                     } ,
  ['diff-editor-next-change']                   = { name = 'arrow-down',                              description = [[Icon for the next change action in the diff editor.]]                                    } ,
  ['diff-editor-previous-change']               = { name = 'arrow-up',                                description = [[Icon for the previous change action in the diff editor.]]                                } ,
  ['diff-editor-toggle-whitespace']             = { name = 'whitespace',                              description = [[Icon for the toggle whitespace action in the diff editor.]]                              } ,
  ['diff-insert']                               = { name = 'add',                                     description = [[Line decoration for inserts in the diff editor.]]                                        } ,
  ['diff-remove']                               = { name = 'remove',                                  description = [[Line decoration for removals in the diff editor.]]                                       } ,
  ['diff-review-close']                         = { name = 'close',                                   description = [[Icon for 'Close' in diff review.]]                                                       } ,
  ['diff-review-insert']                        = { name = 'add',                                     description = [[Icon for 'Insert' in diff review.]]                                                      } ,
  ['diff-review-remove']                        = { name = 'remove',                                  description = [[Icon for 'Remove' in diff review.]]                                                      } ,
  ['explorer-view-icon']                        = { name = 'files',                                   description = [[View icon of the explorer view.]]                                                        } ,
  ['extensions-clear-search-results']           = { name = 'clear-all',                               description = [[Icon for the 'Clear Search Result' action in the extensions view.]]                      } ,
  ['extensions-configure-recommended']          = { name = 'pencil',                                  description = [[Icon for the 'Configure Recommended Extensions' action in the extensions view.]]         } ,
  ['extensions-filter']                         = { name = 'filter',                                  description = [[Icon for the 'Filter' action in the extensions view.]]                                   } ,
  ['extensions-info-message']                   = { name = 'info',                                    description = [[Icon shown with an info message in the extensions editor.]]                              } ,
  ['extensions-install-count']                  = { name = 'cloud-download',                          description = [[Icon shown along with the install count in the extensions view and editor.]]             } ,
  ['extensions-install-local-in-remote']        = { name = 'cloud-download',                          description = [[Icon for the 'Install Local Extension in Remote' action in the extensions view.]]        } ,
  ['extensions-install-workspace-recommended']  = { name = 'cloud-download',                          description = [[Icon for the 'Install Workspace Recommended Extensions' action in the extensions view.]] } ,
  ['extensions-manage']                         = { name = 'gear',                                    description = [[Icon for the 'Manage' action in the extensions view.]]                                   } ,
  ['extensions-rating']                         = { name = 'star',                                    description = [[Icon shown along with the rating in the extensions view and editor.]]                    } ,
  ['extensions-refresh']                        = { name = 'refresh',                                 description = [[Icon for the 'Refresh' action in the extensions view.]]                                  } ,
  ['extensions-remote']                         = { name = 'remote',                                  description = [[Icon to indicate that an extension is remote in the extensions view and editor.]]        } ,
  ['extensions-star-empty']                     = { name = 'star-empty',                              description = [[Empty star icon used for the rating in the extensions editor.]]                          } ,
  ['extensions-star-full']                      = { name = 'star-full',                               description = [[Full star icon used for the rating in the extensions editor.]]                           } ,
  ['extensions-star-half']                      = { name = 'star-half',                               description = [[Half star icon used for the rating in the extensions editor.]]                           } ,
  ['extensions-sync-enabled']                   = { name = 'sync',                                    description = [[Icon to indicate that an extension is synced.]]                                          } ,
  ['extensions-sync-ignored']                   = { name = 'sync-ignored',                            description = [[Icon to indicate that an extension is ignored when syncing.]]                            } ,
  ['extensions-view-icon']                      = { name = 'extensions',                              description = [[View icon of the extensions view.]]                                                      } ,
  ['extensions-warning-message']                = { name = 'warning',                                 description = [[Icon shown with a warning message in the extensions editor.]]                            } ,
  ['find-collapsed']                            = { name = 'chevron-right',                           description = [[Icon to indicate that the editor find widget is collapsed.]]                             } ,
  ['find-expanded']                             = { name = 'chevron-down',                            description = [[Icon to indicate that the editor find widget is expanded.]]                              } ,
  ['find-next-match']                           = { name = 'arrow-down',                              description = [[Icon for 'Find Next' in the editor find widget.]]                                        } ,
  ['find-previous-match']                       = { name = 'arrow-up',                                description = [[Icon for 'Find Previous' in the editor find widget.]]                                    } ,
  ['find-replace']                              = { name = 'replace',                                 description = [[Icon for 'Replace' in the editor find widget.]]                                          } ,
  ['find-replace-all']                          = { name = 'replace-all',                             description = [[Icon for 'Replace All' in the editor find widget.]]                                      } ,
  ['find-selection']                            = { name = 'selection',                               description = [[Icon for 'Find in Selection' in the editor find widget.]]                                } ,
  ['folding-collapsed']                         = { name = 'chevron-right',                           description = [[Icon for collapsed ranges in the editor glyph margin.]]                                  } ,
  ['folding-expanded']                          = { name = 'chevron-down',                            description = [[Icon for expanded ranges in the editor glyph margin.]]                                   } ,
  ['getting-started-beginner']                  = { name = 'lightbulb',                               description = [[Icon used for the beginner category of getting started]]                                 } ,
  ['getting-started-codespaces']                = { name = 'github',                                  description = [[Icon used for the codespaces category of getting started]]                               } ,
  ['getting-started-item-checked']              = { name = 'pass-filled',                             description = [[Used to represent getting started items which have been completed]]                      } ,
  ['getting-started-item-unchecked']            = { name = 'circle-large-outline',                    description = [[Used to represent getting started items which have not been completed]]                  } ,
  ['getting-started-setup']                     = { name = 'heart',                                   description = [[Icon used for the setup category of getting started]]                                    } ,
  ['goto-next-location']                        = { name = 'arrow-down',                              description = [[Icon for goto next editor location.]]                                                    } ,
  ['goto-previous-location']                    = { name = 'arrow-up',                                description = [[Icon for goto previous editor location.]]                                                } ,
  ['keybindings-add']                           = { name = 'add',                                     description = [[Icon for the add action in the keybinding UI.]]                                          } ,
  ['keybindings-edit']                          = { name = 'edit',                                    description = [[Icon for the edit action in the keybinding UI.]]                                         } ,
  ['keybindings-record-keys']                   = { name = 'record-keys',                             description = [[Icon for the 'record keys' action in the keybinding UI.]]                                } ,
  ['keybindings-sort']                          = { name = 'sort-precedence',                         description = [[Icon for the 'sort by precedence' toggle in the keybinding UI.]]                         } ,
  ['loaded-scripts-view-icon']                  = { name = 'debug-alt',                               description = [[View icon of the loaded scripts view.]]                                                  } ,
  ['marker-navigation-next']                    = { name = 'chevron-down',                            description = [[Icon for goto next marker.]]                                                             } ,
  ['marker-navigation-previous']                = { name = 'chevron-up',                              description = [[Icon for goto previous marker.]]                                                         } ,
  ['markers-view-filter']                       = { name = 'filter',                                  description = [[Icon for the filter configuration in the markers view.]]                                 } ,
  ['markers-view-icon']                         = { name = 'warning',                                 description = [[View icon of the markers view.]]                                                         } ,
  ['markers-view-multi-line-collapsed']         = { name = 'chevron-down',                            description = [[Icon indicating that multiple lines are collapsed in the markers view.]]                 } ,
  ['markers-view-multi-line-expanded']          = { name = 'chevron-up',                              description = [[Icon indicating that multiple lines are shown in the markers view.]]                     } ,
  ['notebook-clear']                            = { name = 'clear-all',                               description = [[Icon to clear cell outputs in notebook editors.]]                                        } ,
  ['notebook-collapsed']                        = { name = 'chevron-right',                           description = [[Icon to annotate a collapsed section in notebook editors.]]                              } ,
  ['notebook-delete-cell']                      = { name = 'trash',                                   description = [[Icon to delete a cell in notebook editors.]]                                             } ,
  ['notebook-edit']                             = { name = 'pencil',                                  description = [[Icon to edit a cell in notebook editors.]]                                               } ,
  ['notebook-execute']                          = { name = 'play',                                    description = [[Icon to execute in notebook editors.]]                                                   } ,
  ['notebook-execute-all']                      = { name = 'run-all',                                 description = [[Icon to execute all cells in notebook editors.]]                                         } ,
  ['notebook-expanded']                         = { name = 'chevron-down',                            description = [[Icon to annotate an expanded section in notebook editors.]]                              } ,
  ['notebook-kernel-configure']                 = { name = 'settings-gear',                           description = [[Configure icon in kernel configuration widget in notebook editors.]]                     } ,
  ['notebook-kernel-select']                    = { name = 'server-environment',                      description = [[Configure icon to select a kernel in notebook editors.]]                                 } ,
  ['notebook-mimetype']                         = { name = 'code',                                    description = [[Icon for a mime type in notebook editors.]]                                              } ,
  ['notebook-move-down']                        = { name = 'arrow-down',                              description = [[Icon to move down a cell in notebook editors.]]                                          } ,
  ['notebook-move-up']                          = { name = 'arrow-up',                                description = [[Icon to move up a cell in notebook editors.]]                                            } ,
  ['notebook-open-as-text']                     = { name = 'file-code',                               description = [[Icon to open the notebook in a text editor.]]                                            } ,
  ['notebook-render-output']                    = { name = 'preview',                                 description = [[Icon to render output in diff editor.]]                                                  } ,
  ['notebook-revert']                           = { name = 'discard',                                 description = [[Icon to revert in notebook editors.]]                                                    } ,
  ['notebook-split-cell']                       = { name = 'split-vertical',                          description = [[Icon to split a cell in notebook editors.]]                                              } ,
  ['notebook-state-error']                      = { name = 'error',                                   description = [[Icon to indicate an error state in notebook editors.]]                                   } ,
  ['notebook-state-success']                    = { name = 'check',                                   description = [[Icon to indicate a success state in notebook editors.]]                                  } ,
  ['notebook-stop']                             = { name = 'primitive-square',                        description = [[Icon to stop an execution in notebook editors.]]                                         } ,
  ['notebook-stop-edit']                        = { name = 'check',                                   description = [[Icon to stop editing a cell in notebook editors.]]                                       } ,
  ['notebook-unfold']                           = { name = 'unfold',                                  description = [[Icon to unfold a cell in notebook editors.]]                                             } ,
  ['notifications-clear']                       = { name = 'close',                                   description = [[Icon for the clear action in notifications.]]                                            } ,
  ['notifications-clear-all']                   = { name = 'clear-all',                               description = [[Icon for the clear all action in notifications.]]                                        } ,
  ['notifications-collapse']                    = { name = 'chevron-down',                            description = [[Icon for the collapse action in notifications.]]                                         } ,
  ['notifications-configure']                   = { name = 'gear',                                    description = [[Icon for the configure action in notifications.]]                                        } ,
  ['notifications-expand']                      = { name = 'chevron-up',                              description = [[Icon for the expand action in notifications.]]                                           } ,
  ['notifications-hide']                        = { name = 'chevron-down',                            description = [[Icon for the hide action in notifications.]]                                             } ,
  ['open-editors-view-icon']                    = { name = 'book',                                    description = [[View icon of the open editors view.]]                                                    } ,
  ['outline-view-icon']                         = { name = 'symbol-class',                            description = [[View icon of the outline view.]]                                                         } ,
  ['output-view-icon']                          = { name = 'output',                                  description = [[View icon of the output view.]]                                                          } ,
  ['panel-close']                               = { name = 'close',                                   description = [[Icon to close a panel.]]                                                                 } ,
  ['panel-maximize']                            = { name = 'chevron-up',                              description = [[Icon to maximize a panel.]]                                                              } ,
  ['panel-restore']                             = { name = 'chevron-down',                            description = [[Icon to restore a panel.]]                                                               } ,
  ['parameter-hints-next']                      = { name = 'chevron-down',                            description = [[Icon for show next parameter hint.]]                                                     } ,
  ['parameter-hints-previous']                  = { name = 'chevron-up',                              description = [[Icon for show previous parameter hint.]]                                                 } ,
  ['ports-forward-icon']                        = { name = 'plus',                                    description = [[Icon for the forward action.]]                                                           } ,
  ['ports-open-browser-icon']                   = { name = 'globe',                                   description = [[Icon for the open browser action.]]                                                      } ,
  ['ports-stop-forward-icon']                   = { name = 'x',                                       description = [[Icon for the stop forwarding action.]]                                                   } ,
  ['ports-view-icon']                           = { name = 'plug',                                    description = [[View icon of the remote ports view.]]                                                    } ,
  ['preferences-clear-input']                   = { name = 'clear-all',                               description = [[Icon for clear input in the settings and keybinding UI.]]                                } ,
  ['preferences-open-settings']                 = { name = 'go-to-file',                              description = [[Icon for open settings commands.]]                                                       } ,
  ['private-ports-view-icon']                   = { name = 'lock',                                    description = [[Icon representing a private remote port.]]                                               } ,
  ['public-ports-view-icon']                    = { name = 'eye',                                     description = [[Icon representing a public remote port.]]                                                } ,
  ['refactor-preview-view-icon']                = { name = 'lightbulb',                               description = [[View icon of the refactor preview view.]]                                                } ,
  ['remote-explorer-documentation']             = { name = 'book',                                    description = [[Documentation icon in the remote explorer view.]]                                        } ,
  ['remote-explorer-feedback']                  = { name = 'twitter',                                 description = [[Feedback icon in the remote explorer view.]]                                             } ,
  ['remote-explorer-get-started']               = { name = 'star',                                    description = [[Getting started icon in the remote explorer view.]]                                      } ,
  ['remote-explorer-report-issues']             = { name = 'comment',                                 description = [[Report issue icon in the remote explorer view.]]                                         } ,
  ['remote-explorer-review-issues']             = { name = 'issues',                                  description = [[Review issue icon in the remote explorer view.]]                                         } ,
  ['remote-explorer-view-icon']                 = { name = 'remote-explorer',                         description = [[View icon of the remote explorer view.]]                                                 } ,
  ['review-comment-collapse']                   = { name = 'chevron-up',                              description = [[Icon to collapse a review comment.]]                                                     } ,
  ['run-view-icon']                             = { name = 'debug-alt',                               description = [[View icon of the run view.]]                                                             } ,
  ['search-clear-results']                      = { name = 'clear-all',                               description = [[Icon for clear results in the search view.]]                                             } ,
  ['search-collapse-results']                   = { name = 'collapse-all',                            description = [[Icon for collapse results in the search view.]]                                          } ,
  ['search-details']                            = { name = 'ellipsis',                                description = [[Icon to make search details visible.]]                                                   } ,
  ['search-expand-results']                     = { name = 'expand-all',                              description = [[Icon for expand results in the search view.]]                                            } ,
  ['search-hide-replace']                       = { name = 'chevron-right',                           description = [[Icon to collapse the replace section in the search view.]]                               } ,
  ['search-new-editor']                         = { name = 'new-file',                                description = [[Icon for the action to open a new search editor.]]                                       } ,
  ['search-refresh']                            = { name = 'refresh',                                 description = [[Icon for refresh in the search view.]]                                                   } ,
  ['search-remove']                             = { name = 'close',                                   description = [[Icon to remove a search result.]]                                                        } ,
  ['search-replace']                            = { name = 'replace',                                 description = [[Icon for replace in the search view.]]                                                   } ,
  ['search-replace-all']                        = { name = 'replace-all',                             description = [[Icon for replace all in the search view.]]                                               } ,
  ['search-show-context']                       = { name = 'list-selection',                          description = [[Icon for toggle the context in the search editor.]]                                      } ,
  ['search-show-replace']                       = { name = 'chevron-down',                            description = [[Icon to expand the replace section in the search view.]]                                 } ,
  ['search-stop']                               = { name = 'search-stop',                             description = [[Icon for stop in the search view.]]                                                      } ,
  ['search-view-icon']                          = { name = 'search',                                  description = [[View icon of the search view.]]                                                          } ,
  ['settings-add']                              = { name = 'add',                                     description = [[Icon for the add action in the Settings UI.]]                                            } ,
  ['settings-discard']                          = { name = 'discard',                                 description = [[Icon for the discard action in the Settings UI.]]                                        } ,
  ['settings-edit']                             = { name = 'edit',                                    description = [[Icon for the edit action in the Settings UI.]]                                           } ,
  ['settings-folder-dropdown']                  = { name = 'triangle-down',                           description = [[Icon for the folder dropdown button in the split JSON Settings editor.]]                 } ,
  ['settings-group-collapsed']                  = { name = 'chevron-right',                           description = [[Icon for a collapsed section in the split JSON Settings editor.]]                        } ,
  ['settings-group-expanded']                   = { name = 'chevron-down',                            description = [[Icon for an expanded section in the split JSON Settings editor.]]                        } ,
  ['settings-more-action']                      = { name = 'gear',                                    description = [[Icon for the 'more actions' action in the Settings UI.]]                                 } ,
  ['settings-remove']                           = { name = 'close',                                   description = [[Icon for the remove action in the Settings UI.]]                                         } ,
  ['settings-sync-view-icon']                   = { name = 'sync',                                    description = [[View icon of the Settings Sync view.]]                                                   } ,
  ['settings-view-bar-icon']                    = { name = 'settings-gear',                           description = [[Settings icon in the view bar.]]                                                         } ,
  ['source-control-view-icon']                  = { name = 'source-control',                          description = [[View icon of the Source Control view.]]                                                  } ,
  ['suggest-more-info']                         = { name = 'chevron-right',                           description = [[Icon for more information in the suggest widget.]]                                       } ,
  ['tasks-list-configure']                      = { name = 'gear',                                    description = [[Configuration icon in the tasks selection list.]]                                        } ,
  ['tasks-remove']                              = { name = 'close',                                   description = [[Icon for remove in the tasks selection list.]]                                           } ,
  ['terminal-kill']                             = { name = 'trash',                                   description = [[Icon for killing a terminal instance.]]                                                  } ,
  ['terminal-new']                              = { name = 'add',                                     description = [[Icon for creating a new terminal instance.]]                                             } ,
  ['terminal-rename']                           = { name = 'gear',                                    description = [[Icon for rename in the terminal quick menu.]]                                            } ,
  ['terminal-view-icon']                        = { name = 'terminal',                                description = [[View icon of the terminal view.]]                                                        } ,
  ['test-view-icon']                            = { name = 'beaker',                                  description = [[View icon of the test view.]]                                                            } ,
  ['testing-cancel-icon']                       = { name = 'close',                                   description = [[Icon to cancel ongoing test runs.]]                                                      } ,
  ['testing-debug-icon']                        = { name = 'debug-alt',                               description = [[Icon of the "debug test" action.]]                                                       } ,
  ['testing-error-icon']                        = { name = 'warning',                                 description = [[Icon shown for tests that have an error.]]                                               } ,
  ['testing-failed-icon']                       = { name = 'close',                                   description = [[Icon shown for tests that failed.]]                                                      } ,
  ['testing-passed-icon']                       = { name = 'pass',                                    description = [[Icon shown for tests that passed.]]                                                      } ,
  ['testing-queued-icon']                       = { name = 'watch',                                   description = [[Icon shown for tests that are queued.]]                                                  } ,
  ['testing-run-all-icon']                      = { name = 'run-all',                                 description = [[Icon of the "run all tests" action.]]                                                    } ,
  ['testing-run-icon']                          = { name = 'run',                                     description = [[Icon of the "run test" action.]]                                                         } ,
  ['testing-show-as-list-icon']                 = { name = 'list-tree',                               description = [[Icon shown when the test explorer is disabled as a tree.]]                               } ,
  ['testing-skipped-icon']                      = { name = 'debug-step-over',                         description = [[Icon shown for tests that are skipped.]]                                                 } ,
  ['testing-unset-icon']                        = { name = 'circle-outline',                          description = [[Icon shown for tests that are in an unset state.]]                                       } ,
  ['timeline-open']                             = { name = 'history',                                 description = [[Icon for the open timeline action.]]                                                     } ,
  ['timeline-pin']                              = { name = 'pin',                                     description = [[Icon for the pin timeline action.]]                                                      } ,
  ['timeline-refresh']                          = { name = 'refresh',                                 description = [[Icon for the refresh timeline action.]]                                                  } ,
  ['timeline-unpin']                            = { name = 'pinned',                                  description = [[Icon for the unpin timeline action.]]                                                    } ,
  ['timeline-view-icon']                        = { name = 'history',                                 description = [[View icon of the timeline view.]]                                                        } ,
  ['variables-view-icon']                       = { name = 'debug-alt',                               description = [[View icon of the variables view.]]                                                       } ,
  ['view-pane-container-collapsed']             = { name = 'chevron-right',                           description = [[Icon for a collapsed view pane container.]]                                              } ,
  ['view-pane-container-expanded']              = { name = 'chevron-down',                            description = [[Icon for an expanded view pane container.]]                                              } ,
  ['watch-expressions-add']                     = { name = 'add',                                     description = [[Icon for the add action in the watch view.]]                                             } ,
  ['watch-expressions-add-function-breakpoint'] = { name = 'add',                                     description = [[Icon for the add function breakpoint action in the watch view.]]                         } ,
  ['watch-expressions-remove-all']              = { name = 'close-all',                               description = [[Icon for the Remove All action in the watch view.]]                                      } ,
  ['watch-view-icon']                           = { name = 'debug-alt',                               description = [[View icon of the watch view.]]                                                           } ,
  ['widget-close']                              = { name = 'close',                                   description = [[Icon for the close action in widgets.]]                                                  } ,
}
