local SymbolKind = {
  File          = { index = { lsp =  1, vscode =  0 }, unicode = '', codicon = ' ' },
  Module        = { index = { lsp =  2, vscode =  1 }, unicode = '', codicon = ' ' },
  Namespace     = { index = { lsp =  3, vscode =  2 }, unicode = '', codicon = ' ' },
  Package       = { index = { lsp =  4, vscode =  3 }, unicode = '', codicon = ' ' },
  Class         = { index = { lsp =  5, vscode =  4 }, unicode = '', codicon = ' ' },
  Method        = { index = { lsp =  6, vscode =  5 }, unicode = '', codicon = ' ' },
  Property      = { index = { lsp =  7, vscode =  6 }, unicode = '', codicon = ' ' },
  Field         = { index = { lsp =  8, vscode =  7 }, unicode = '', codicon = ' ' },
  Constructor   = { index = { lsp =  9, vscode =  8 }, unicode = '', codicon = ' ' },
  Enum          = { index = { lsp = 10, vscode =  9 }, unicode = '', codicon = ' ' },
  Interface     = { index = { lsp = 11, vscode = 10 }, unicode = '', codicon = ' ' },
  Function      = { index = { lsp = 12, vscode = 11 }, unicode = '', codicon = ' ' },
  Variable      = { index = { lsp = 13, vscode = 12 }, unicode = '', codicon = ' ' },
  Constant      = { index = { lsp = 14, vscode = 13 }, unicode = '', codicon = ' ' },
  String        = { index = { lsp = 15, vscode = 14 }, unicode = '', codicon = ' ' },
  Number        = { index = { lsp = 16, vscode = 15 }, unicode = '', codicon = ' ' },
  Boolean       = { index = { lsp = 17, vscode = 16 }, unicode = '', codicon = ' ' },
  Array         = { index = { lsp = 18, vscode = 17 }, unicode = '', codicon = ' ' },
  Object        = { index = { lsp = 19, vscode = 18 }, unicode = '', codicon = ' ' },
  Key           = { index = { lsp = 20, vscode = 19 }, unicode = '', codicon = ' ' },
  Null          = { index = { lsp = 21, vscode = 20 }, unicode = '', codicon = ' ' },
  EnumMember    = { index = { lsp = 22, vscode = 21 }, unicode = '', codicon = ' ' },
  Struct        = { index = { lsp = 23, vscode = 22 }, unicode = '', codicon = ' ' },
  Event         = { index = { lsp = 24, vscode = 23 }, unicode = '', codicon = ' ' },
  Operator      = { index = { lsp = 25, vscode = 24 }, unicode = '', codicon = ' ' },
  TypeParameter = { index = { lsp = 26, vscode = 25 }, unicode = '', codicon = ' ' },
}

return SymbolKind
